services:
  redis:
    container_name: redis-db
    image: redis:8.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  redis-data:
    driver: local
