import type { Product } from "../../types/product.js";

export abstract class BaseDatabase {
  /**
   * Saves products to the database.
   * Should return the saved products (ideally with IDs if generated by the DB).
   */
  abstract saveProducts(products: Product[]): Promise<Product[]>;

  /**
   * Ensures that image tracking rows exist for the given products.
   */
  abstract ensureProductImageRows(products: Product[]): Promise<void>;

  /**
   * Uploads the card screenshot for a product to storage and updates the database.
   */
  abstract uploadCardScreenshot(product: Product): Promise<void>;
}
